import Head from "next/head";
import Image from "next/image";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>hello</h1>
        <p>
          Sint amet nostrud reprehenderit anim dolore proident ea. Cupidatat
          irure reprehenderit ullamco laboris nulla et excepteur ut in eiusmod
          duis. Ad laborum consequat in fugiat. Officia voluptate ullamco nulla
          ex ut. Nulla proident nisi veniam aute voluptate. Exercitation culpa
          ex veniam sunt qui adipisicing id.
        </p>
        <button className="btn">Sign up</button>
        <button className="btn btn--primary">Sign up</button>
        <a href="" className="btn">
          Sign up
        </a>
        <a href="" className="btn btn--primary">
          Sign up
        </a>
        <h3>Welcome h3</h3>
        <h2>Welcome h2</h2>
        <h5>Welcome h5</h5>
        <h4>Welcome h4</h4>
        <h6>Welcome h6</h6>
        <a href="">www.xxxxx.com</a>
      </main>

      <footer>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
